### ISSUE TITLE
Hey guys I found a bug in the compiler

### ISSUE THREAD

**Issue by ArmeniaH** [medialize/sass.js#46] opened 2016-02-12 12:41 UTC
Assume this scss code

.class1, .class2 {
div:not(.last) {
		background:red;
	}
}

After compiling I get

.class1 div:not(.last, .last), .class2 div:not(.last, .last) {
background: red;
}
____________________

another example 

.class1, .class2, .class3, .class4 {
div:not(.last) {
		background:red;
	}
}

.class1 div:not(.last, .last, .last, .last), .class2 div:not(.last, .last, .last, .last), .class3 div:not(.last, .last, .last, .last), .class4 div:not(.last, .last, .last, .last) {
background: red;
}

As you can see the .last class is getting duplicated by the number of global class counts.

**Comment by rodneyrehm** [comment] 2016-02-12 13:18
I took the liberty of formatting your code examples.

The issue is already known and tracked at sass/libsass#1901. There is nothing sass.js can do about errors in libsass itself. Closing this issue because of upstream problem.

**Closed by rodneyrehm** 2016-02-12 13:18 UTC
