### ISSUE TITLE
Disabling automatic file extension affix to avoid '.scss.scss' when explicit imports are used

### ISSUE THREAD

**Issue by KevCJones** [medialize/sass.js#51] opened 2016-04-12 23:15 UTC
Related to an issue i'm looking into [here ](https://github.com/mobilexag/plugin-sass/issues/43)

I notice on your playground this issue is not present. However, if we try to use explicit extensions in the @import like this :

```
@import './b';

@import './c.scss';

@import './d';
```

inside a file `a.scss`. sass.js attempts to resolve `c.scss.scss`. I'm able to capture this in the `importer` function and replace double extensions. But wondering if perhaps you have a better way to avoid this problem?

**Comment by KevCJones** [comment] 2016-04-13 09:01
Sorry i just read the issue guideline so i've probably noted something that isn't your problem! Going to libsass

**Comment by rodneyrehm** [comment] 2016-04-13 09:15
The importer callback is very much the issue of sass.js. The extension duplication is caused by [_libsassPathVariations](https://github.com/medialize/sass.js/blob/master/src/sass.importer.js#L61-L82)

**Comment by KevCJones** [comment] 2016-04-13 09:26
Thanks - i actually went and did my due diligence and double checked using node-sass and indeed. It didn't have any trouble parsing the same file. Reviewing the 'included files' 

```
includedFiles:
      [ '/Users/KevinJones/work/gits/jspmSassPluginBug/src/a.scss',
        '/Users/KevinJones/work/gits/jspmSassPluginBug/src/_b.scss',
        '/Users/KevinJones/work/gits/jspmSassPluginBug/src/_c.scss',
        '/Users/KevinJones/work/gits/jspmSassPluginBug/src/_d.scss' ],
```
So the immediate question is how to resolve the issue? I could look into if no one else has time.

**Comment by rodneyrehm** [comment] 2016-04-13 14:10
> The extension duplication is caused by _libsassPathVariations

Maybe I shouldn't comment on issues before the first coffee. My statement was wrong, see explanation below.

> I notice on your playground this issue is not present.

The playground does not use an [Importer Callback](https://github.com/medialize/sass.js/#importer-callback-function), so file resolution is left to libsass. 

You're using an [importer](https://github.com/mobilexag/plugin-sass/blob/master/src/sass-inject.js#L30-L52). With that you are in complete control of how files are resolved. This [line](https://github.com/mobilexag/plugin-sass/blob/master/src/sass-inject.js#L51) should probably call `done({ error: 'your message here' })` instead?

You [prefix files with an underscore](https://github.com/mobilexag/plugin-sass/blob/master/src/sass-inject.js#L37) which is not universally true. It also seems like your [resolve-path.js](https://github.com/mobilexag/plugin-sass/blob/master/src/resolve-path.js#L20) is adding `.scss` to the filename.

---

```scss
@import "hello";
```

is resolved by libsass in the following order:

```js
[
  'hello',
  '_hello',
  '_hello.scss',
  '_hello.sass',
  '_hello.css',
  'hello.scss',
  'hello.sass',
  'hello.css'
]
```

It seems you have hardcoded the third variant. And that's why the first does not resolve anymore.

**Comment by KevCJones** [comment] 2016-04-13 15:33
> Maybe I shouldn't comment on issues before the first coffee. My statement was wrong, see explanation below.

Hah, yeah can't say you're alone there. In a similar vein, i should hold back on patching my own library until i fully understand the problem. Thanks for the breakdown, its triggered a Eurika moment, and i think i know where we've borked the path...  If its right i'll close this issue as its 99% looking like its an internal issue.

**Comment by rodneyrehm** [comment] 2016-04-13 15:53
Let me know if you require the filename list generated by [libsassPathVariations()](https://github.com/medialize/sass.js/blob/master/src/sass.importer.js#L61-L82) passed to the [importer callback](https://github.com/medialize/sass.js/blob/master/src/sass.importer.js#L25-L31). Otherwise good luck!

**Closed by rodneyrehm** 2016-04-13 15:53 UTC

**Comment by KevCJones** [comment] 2016-04-13 16:28
Thanks - I don't think we'll need that for the moment but. In the end it was such an obvious error i felt bad i didn't see it a day ago - clearly not enough coffee was used.  [Pull Request Here](https://github.com/mobilexag/plugin-sass/pull/50/commits/6dfe952c74bcd49b7f8f203c2b5bb8176e840a36) - thanks for the explanations though, its been educational.
